services:

  backend:
    build: ./backend
    container_name: yl40-backend

    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/ttyS0:/dev/ttyS0"

    privileged: true

    volumes:
      - /home/pi/yl40iot.db:/home/pi/yl40iot.db

    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-}

    restart: unless-stopped

  nginx:
    image: nginx:alpine

    container_name: yl40-nginx

    ports:
      - "80:80"

    volumes:
      - ./frontend:/usr/share/nginx/html

      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend

    restart: unless-stopped
